
#INBOUND:

INBOUND_LOGIN_EMAIL = "mpeters@energypluscompany.com"
INBOUND_LOGIN_PASSWORD = "energy"
INBOUND_LOGIN_URL = "http://www.pt.energypluscompany.com/myinbound/login.php"
INBOUND_RESETSESSION_URL = "http://www.pt.energypluscompany.com/resetsession.php"

#START A MANUAL CALL
INBOUND_STARTMANUALCALL_PHONENUMBER = "5454588883"
INBOUND_STARTMANUALCALL_REASON = "this is a test"

##Dispositions

INBOUND_500DISP_FIRSTNAME = "EP"
INBOUND_500DISP_LASTNAME = "dns"
INBOUND_500DISP_ADDRESS1 = "123 main st"
INBOUND_500DISP_CITY = "fairless hills"
INBOUND_500DISP_ZIP = "19030"
INBOUND_500DISP_EMAIL = "test@test.com"
INBOUND_500DISP_AREACODE = "215"
INBOUND_500DISP_PREFIX = "493"
INBOUND_500DISP_LINENUMBER = "4342"
INBOUND_500DISP_NOTES = "testin"
INBOUND_LOGDISP_DISPOCOMMENTS = "test"

